name: Release
on:
  push:
    tags:
      - 'v*.*.*'
env:
  GOARCH: amd64
  GOOS: linux
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.9

    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Include the license of Go in LICENSE for binary distribution
      run: |
        cat >> LICENSE <<EOS


        The binary includes the Go runtime and the standard library, which are
        distributed under the following license:

        EOS
        curl -s -L https://golang.org/LICENSE?m=text >> LICENSE

    - name: Build the binary
      run: go build -ldflags '-s -w' -trimpath
      env:
        CGO_ENABLED: 0

    - name: Get the release version
      id: get_release_version
      run: |
        VERSION=$(basename ${{ github.ref }})
        echo version=${VERSION} >> $GITHUB_OUTPUT
        echo prerelease=$(case ${VERSION} in *-*) echo true ;; *) echo false; esac) >> $GITHUB_OUTPUT

    - name: Archive files
      id: archive
      run: |
        DIR=sidenote_${{ steps.get_release_version.outputs.version }}_${{ env.GOOS }}_${{ env.GOARCH }}
        ARCHIVE=${DIR}.tar.gz
        SHA256SUM=${DIR}.sha256sum
        mkdir ${DIR}
        cp -a CHANGELOG.md LICENSE README.md sidenote ${DIR}
        tar -czf ${ARCHIVE} ${DIR}
        sha256sum ${ARCHIVE} > ${SHA256SUM}
        echo archive=${ARCHIVE} >> $GITHUB_OUTPUT
        echo sha256sum=${SHA256SUM} >> $GITHUB_OUTPUT

    - name: Create a release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.get_release_version.outputs.version }}
        prerelease: ${{ steps.get_release_version.outputs.prerelease }}
        files: |
          ${{ steps.archive.outputs.archive }}
          ${{ steps.archive.outputs.sha256sum }}
