name: Release
on:
  push:
    tags:
      - 'v*.*.*'
env:
  GOARCH: amd64
  GOOS: linux
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3

    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Include the license of Go in LICENSE for binary distribution
      run: |
        cat >> LICENSE <<EOS


        The binary includes the Go runtime and the standard library, which are
        distributed under the following license:

        EOS
        curl -s -L https://golang.org/LICENSE?m=text >> LICENSE

    - name: Build the binary
      run: go build -ldflags '-s -w' -trimpath
      env:
        CGO_ENABLED: 0

    - name: Get the release version
      id: get_release_version
      run: |
        VERSION=$(basename ${{ github.ref }})
        echo version=${VERSION} >> $GITHUB_OUTPUT
        echo prerelease=$(case ${VERSION} in *-*) echo true ;; *) echo false; esac) >> $GITHUB_OUTPUT

    - name: Archive files
      id: archive
      run: |
        DIR=sidenote_${{ steps.get_release_version.outputs.version }}_${{ env.GOOS }}_${{ env.GOARCH }}
        ARCHIVE=${DIR}.tar.gz
        SHA256SUM=${DIR}.sha256sum
        mkdir ${DIR}
        cp -a CHANGELOG.md LICENSE README.md sidenote ${DIR}
        tar -czf ${ARCHIVE} ${DIR}
        sha256sum ${ARCHIVE} > ${SHA256SUM}
        echo archive=${ARCHIVE} >> $GITHUB_OUTPUT
        echo sha256sum=${SHA256SUM} >> $GITHUB_OUTPUT

    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: ${{ steps.get_release_version.outputs.prerelease }}

    - name: Upload the archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.archive.outputs.archive }}
        asset_name: ${{ steps.archive.outputs.archive }}
        asset_content_type: application/gzip

    - name: Upload the sha256sum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.archive.outputs.sha256sum }}
        asset_name: ${{ steps.archive.outputs.sha256sum }}
        asset_content_type: text/plain
