name: Test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*.*.*'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.26.7

      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Run tests
        run: make test
